"""
TerraFlare - Model Evaluator Module
Runs evaluation on trained YOLO11 model checkpoints and extracts real precision, recall, F1, mAP@50, and mAP@50-95 metrics.
"""

import os
import pandas as pd
from ultralytics import YOLO

def extract_metrics_from_val_results(val_results):
    """
    Extracts precision, recall, F1, mAP50, and mAP50-95 from Ultralytics val() object.
    """
    metrics = {
        "precision": 0.0,
        "recall": 0.0,
        "f1": 0.0,
        "map50": 0.0,
        "map50_95": 0.0
    }

    try:
        # Access box metrics directly if available
        if hasattr(val_results, 'box'):
            box = val_results.box
            metrics["precision"] = float(box.mp) if hasattr(box, 'mp') else 0.0
            metrics["recall"] = float(box.mr) if hasattr(box, 'mr') else 0.0
            metrics["map50"] = float(box.map50) if hasattr(box, 'map50') else 0.0
            metrics["map50_95"] = float(box.map) if hasattr(box, 'map') else 0.0
        elif hasattr(val_results, 'results_dict'):
            rd = val_results.results_dict
            metrics["precision"] = float(rd.get('metrics/precision(B)', 0.0))
            metrics["recall"] = float(rd.get('metrics/recall(B)', 0.0))
            metrics["map50"] = float(rd.get('metrics/mAP50(B)', 0.0))
            metrics["map50_95"] = float(rd.get('metrics/mAP50-95(B)', 0.0))
    except Exception:
        pass

    # Compute F1 score: 2 * (P * R) / (P + R)
    p = metrics["precision"]
    r = metrics["recall"]
    if p + r > 0:
        metrics["f1"] = 2.0 * (p * r) / (p + r)
    else:
        metrics["f1"] = 0.0

    return metrics

def extract_metrics_from_csv(results_csv_path):
    """
    Fallback: Reads evaluation metrics from results.csv generated by Ultralytics.
    """
    metrics = {
        "precision": 0.0,
        "recall": 0.0,
        "f1": 0.0,
        "map50": 0.0,
        "map50_95": 0.0
    }
    
    if not results_csv_path or not os.path.exists(results_csv_path):
        return metrics

    try:
        df = pd.read_csv(results_csv_path)
        # Strip spaces from column headers
        df.columns = [c.strip() for c in df.columns]
        
        # Get last row (final epoch)
        last_row = df.iloc[-1]
        
        # Look for metric columns
        for col in df.columns:
            if 'precision' in col.lower():
                metrics["precision"] = float(last_row[col])
            elif 'recall' in col.lower():
                metrics["recall"] = float(last_row[col])
            elif 'map50-95' in col.lower() or 'map_0.5:0.95' in col.lower():
                metrics["map50_95"] = float(last_row[col])
            elif 'map50' in col.lower() or 'map_0.5' in col.lower():
                metrics["map50"] = float(last_row[col])

        p = metrics["precision"]
        r = metrics["recall"]
        metrics["f1"] = 2.0 * (p * r) / (p + r) if (p + r) > 0 else 0.0
    except Exception:
        pass

    return metrics

def evaluate_yolo_model(weights_path, data_yaml_path, device="cpu"):
    """
    Evaluates a trained YOLO model on the validation dataset.
    Returns metrics dict.
    """
    if not os.path.exists(weights_path):
        raise FileNotFoundError(f"Trained model weights not found at {weights_path}")

    model = YOLO(weights_path)
    val_res = model.val(data=data_yaml_path, split="val", device=device, verbose=False)
    metrics = extract_metrics_from_val_results(val_res)
    return metrics
